version: '3.1'

services:

  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: 'artwalk'
      MYSQL_USER: 'artwalk'
      MYSQL_PASSWORD: 'artwalk_password'
      MYSQL_ROOT_PASSWORD: 'artwalk_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - artwalkNet

networks:
  artwalkNet: